### ISSUE TITLE
Elastic beanstalk deployment question: atal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by imgarylai** [shakacode/react_on_rails#1049]
Hello, 

I'm trying to deploy my app to aws through elastic beanstalk. The file `yarn.config` from this [repo](https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/elastic-beanstalk.md) has been adding to the `.ebextensions` directory. Messages below shows the reason causing deployment failure. Is anyone familiar with elastic beanstalk can understand what causes this happen?

```sh
+ cd /var/app/ondeck
+ su -s /bin/bash -c 'bundle exec /opt/elasticbeanstalk/support/scripts/check-for-rake-task.rb assets:precompile' webapp
fatal: Not a git repository (or any of the parent directories): .git
+ '[' false == true ']'
+ su -s /bin/bash -c 'bundle exec rake assets:precompile' webapp
fatal: Not a git repository (or any of the parent directories): .git
ReactOnRails: Set generated_assets_dir to default: public/webpack/production
RAILS_ENV=production bin/webpack
fatal: Not a git repository (or any of the parent directories): .git
/opt/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/webpacker-3.3.1/lib/webpacker/webpack_runner.rb:11:in `exec': No such file or directory - /var/app/ondeck/node_modules/.bin/webpack (Errno::ENOENT)
from /opt/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/webpacker-3.3.1/lib/webpacker/webpack_runner.rb:11:in `block in run'
from /opt/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/webpacker-3.3.1/lib/webpacker/webpack_runner.rb:10:in `chdir'
from /opt/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/webpacker-3.3.1/lib/webpacker/webpack_runner.rb:10:in `run'
from /opt/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/webpacker-3.3.1/lib/webpacker/runner.rb:6:in `run'
from bin/webpack:15:in `<main>'
rake aborted!
Command failed with status (1): [RAILS_ENV=production bin/webpack...]
/opt/rubies/ruby-2.5.0/bin/bundle:23:in `load'
/opt/rubies/ruby-2.5.0/bin/bundle:23:in `<main>'
Tasks: TOP => assets:precompile => react_on_rails:assets:compile_environment => react_on_rails:assets:webpack
(See full trace by running task with --trace).
```

I follow the steps on readme and works fine on my machine. Also,`RAILS_ENV=production bundle exec rake assets:precompile` works find on my laptop. 

My environment is 
```sh
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
Rails 5.2.0.rc2
```

Here is my `Gemfile`
```rb
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.0.rc2'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.18'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
# gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Bootsnap is a library that plugs into Ruby, with optional support for ActiveSupport and YAML, to optimize and cache expensive computations.
gem 'bootsnap', require: false

gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'bootstrap', '~> 4.0.0'
gem 'font-awesome-rails'
gem "react_on_rails", "10.0.0"
gem "webpacker", "~> 3.0"
gem 'mini_racer', platforms: :ruby

gem 'devise'
gem 'devise-async'
gem 'omniauth'
gem 'cancancan'
gem 'rolify'
gem 'administrate'
gem 'ckeditor'
gem 'administrate-field-ckeditor'
gem 'rails_sortable'
gem 'devise-bootstrap-views', github: 'hisea/devise-bootstrap-views', branch: 'bootstrap4'

gem 'simple_form'
gem 'client_side_validations'
gem 'client_side_validations-simple_form'

gem 'rack-cors', require: 'rack/cors'
gem 'rack-attack'

gem 'carrierwave', '~> 1.0'
gem 'carrierwave-base64'
# gem 'paperclip'
gem 'carrierwave-aws'
gem 'mini_magick'
# gem 'fog-aws'
gem 'aws-sdk'

gem 'meta-tags'
gem 'friendly_id', '~> 5.1.0' # Note: You MUST use 5.0.0 or greater for Rails 4.0+

# state machine
gem 'aasm'

# i18n
gem 'rails-i18n', '~> 5.0.0' # For 5.0.x and 5.1.x
gem 'devise-i18n'
gem 'i18n-country-translations'
gem 'i18n-tasks'

# background job
gem 'sidekiq'
gem 'sinatra', :require => nil

# Cron job
gem 'whenever', require: false

# Rails engine for static pages.
gem 'high_voltage', '~> 3.0.0'

# Generate Heroku-like memorable random names to use in your apps or anywhere else.
gem 'haikunator'

gem 'health_check'

# Ruby tools
gem 'smarter_csv'

# retry
gem 'retriable', '~> 3.1'

gem 'rspec_api_documentation'

# hotfix
gem 'ffi', '1.9.18'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
  gem 'dotenv-rails'

  gem 'database_cleaner'
  # Use RSpec for specs
  gem 'rspec-rails', '>= 3.5.0'

  # Use Factory Bot for generating random test data
  gem 'factory_bot_rails'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  gem 'bullet'
  gem 'rack-mini-profiler'
  gem 'xray-rails'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'awesome_print'
  gem 'annotate'
  gem 'faker'

  # # Deployment
  # gem 'capistrano'
  # gem 'capistrano-bundler'
  # gem 'capistrano-rails'

  gem 'rubocop', require: false

  gem 'rails_real_favicon'
  gem 'git'
  gem 'pgreset'
  gem 'highline'

  # email
  gem 'letter_opener'
  gem 'letter_opener_web'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'decoder', path: 'decoder'
```

**Comment by imgarylai** [comment]
I solve this issue by creating the config file below, but I have a new issue that all my pack assets get 404.

```
files:
  "/opt/elasticbeanstalk/hooks/appdeploy/pre/09_yarn.sh" :
    mode: "000755"
    owner: root
    group: root
    content: |
      #!/usr/bin/env bash
      set -xe

      EB_SCRIPT_DIR=$(/opt/elasticbeanstalk/bin/get-config container -k script_dir)
      EB_APP_STAGING_DIR=$(/opt/elasticbeanstalk/bin/get-config container -k app_staging_dir)
      EB_APP_USER=$(/opt/elasticbeanstalk/bin/get-config container -k app_user)
      EB_SUPPORT_DIR=$(/opt/elasticbeanstalk/bin/get-config container -k support_dir)

      . $EB_SUPPORT_DIR/envvars
      . $EB_SCRIPT_DIR/use-app-ruby.sh

      # Install nodejs
      echo "install nodejs"
      curl --silent --location https://rpm.nodesource.com/setup_6.x | sudo bash -
      yum -y install nodejs
      echo "install yarn"
      # install yarn
      wget https://dl.yarnpkg.com/rpm/yarn.repo -O /etc/yum.repos.d/yarn.repo;
      yum -y install yarn;

      # yarn install
      cd $EB_APP_STAGING_DIR
      yarn

      # mkdir /home/webapp
      mkdir -p /home/webapp
      chown webapp:webapp /home/webapp
      chmod 700 /home/webapp
```

**Comment by imgarylai** [comment]
I solve this problem. It's because `nginx`. For people who use elastic beanstalk with rails please remember add the location of `/packs`. 

It's like something below in your `/etc/nginx/conf.d/proxy.conf`
```
          location /packs {
            root /var/app/current/public;
          }
```

**Comment by justin808** [comment]
@imgarylai thank you for your work on this. Could you please submit a doc PR on this?

This is the file to change: https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/elastic-beanstalk.md
