### ISSUE TITLE
Issue with Addressable parsing Rails server info inside `react_component` on Capybara headless tests

### ISSUE THREAD

**Issue by mechabyte** [shakacode/react_on_rails#1104]
Hey, just wanted to say thanks for contributing this library which makes it super simple to integrate React components into legacy Rails applications. Everything has been pretty straightforward so far, but I've been running into some issues when running some headless tests using Capybara. Specifically, the `Addressable` gem gets tripped up when using the `react_component` view helper ([gathering Rails context](https://github.com/shakacode/react_on_rails/blob/master/lib/react_on_rails/react_on_rails_helper.rb#L510-L535)) inside of our app's haml views due to an invalid port number. 

Our existing tests were using Capybara Webkit, which I've read can cause issues with passing invalid or blank ports. I tried swapping out the driver to Selenium to no avail.  I was thinking the solution could be using a proxy within Capybara's settings, but wasn't sure if I was missing something simpler. I've gone through the repo's RSpec dummy example, which notes using PhantomJS as a headless browser. Do you think this would be a more appropriate solution, or should we just pull out the testing of the React component to something separate & JS-based like Enzyme? 

I've attached the `ActionView::TemplateError` block of below:

```ruby

     # /var/lib/gems/2.3.0/gems/react_on_rails-10.0.2/app/helpers/react_on_rails_helper.rb:269:in `build_react_component_result_for_server_rendered_string'
     # /var/lib/gems/2.3.0/gems/react_on_rails-10.0.2/app/helpers/react_on_rails_helper.rb:105:in `react_component'
     # ./app/views/controls/_snippet.html.haml:228:in `_app_views_controls__snippet_html_haml__746596864835777334_253774320'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/template.rb:157:in `block in render'
     # /var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `block in instrument'
     # /var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
     # /var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `instrument'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/template.rb:352:in `instrument_render_template'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/template.rb:155:in `render'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/partial_renderer.rb:342:in `block in render_partial'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
     # /var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `block in instrument'
     # /var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
     # /var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `instrument'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/partial_renderer.rb:331:in `render_partial'
     # /var/lib/gems/2.3.0/gems/ddtrace-0.11.4/lib/ddtrace/contrib/rails/core_extensions.rb:122:in `render_partial_with_datadog'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/partial_renderer.rb:310:in `render'
     # /var/lib/gems/2.3.0/gems/ddtrace-0.11.4/lib/ddtrace/contrib/rails/core_extensions.rb:98:in `render_with_datadog'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/renderer.rb:47:in `render_partial'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/helpers/rendering_helper.rb:35:in `render'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/test_case.rb:203:in `render'
     # ./app/views/controls/show.html.haml:131:in `_app_views_controls_show_html_haml__1460547735093567258_271711160'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/template.rb:157:in `block in render'
     # /var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `block in instrument'
     # /var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
     # /var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `instrument'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/template.rb:352:in `instrument_render_template'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/template.rb:155:in `render'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/template_renderer.rb:52:in `block (2 levels) in render_template'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
     # /var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `block in instrument'
     # /var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
     # /var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `instrument'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/template_renderer.rb:51:in `block in render_template'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/template_renderer.rb:59:in `render_with_layout'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/template_renderer.rb:50:in `render_template'
     # /var/lib/gems/2.3.0/gems/ddtrace-0.11.4/lib/ddtrace/contrib/rails/core_extensions.rb:70:in `render_template_with_datadog'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/template_renderer.rb:14:in `render'
     # /var/lib/gems/2.3.0/gems/ddtrace-0.11.4/lib/ddtrace/contrib/rails/core_extensions.rb:38:in `render_with_datadog'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/renderer.rb:42:in `render_template'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/renderer.rb:23:in `render'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/helpers/rendering_helper.rb:32:in `render'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/test_case.rb:203:in `render'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/test_case.rb:119:in `render'
     # ./spec/views/controls/show.haml.haml_spec.rb:110:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Addressable::URI::InvalidURIError:
     #   Invalid port number: "controller=>\"controls\"}"
     #   /var/lib/gems/2.3.0/gems/addressable-2.5.2/lib/addressable/uri.rb:1373:in `port='
  7) controls/show auto adjust pane should not show disabled zones
     Failure/Error: = react_component("EventsCard", props: { events: events.map{|event| { "title" => sanitize(event.as_text.gsub(/\n/,'<br/>').html_safe, tags: ['br']), "description" => event.event_tooltip, "id" => event.id, "eventType" => event.event_type, "isFault" => event.is_fault, "createdAt" => event.created_at }}, eventsViewAllPath: events_control_path(@control), eventsClearFaultsPath: clear_all_faults_control_path(@control) })
     ActionView::Template::Error:
       Invalid port number: "controller=>\"controls\"}"
     # /var/lib/gems/2.3.0/gems/addressable-2.5.2/lib/addressable/uri.rb:1373:in `port='
     # /var/lib/gems/2.3.0/gems/addressable-2.5.2/lib/addressable/uri.rb:804:in `block in initialize'
     # /var/lib/gems/2.3.0/gems/addressable-2.5.2/lib/addressable/uri.rb:2355:in `defer_validation'
     # /var/lib/gems/2.3.0/gems/addressable-2.5.2/lib/addressable/uri.rb:796:in `initialize'
     # /var/lib/gems/2.3.0/gems/addressable-2.5.2/lib/addressable/uri.rb:136:in `new'
     # /var/lib/gems/2.3.0/gems/addressable-2.5.2/lib/addressable/uri.rb:136:in `parse'
     # /var/lib/gems/2.3.0/gems/react_on_rails-10.0.2/app/helpers/react_on_rails_helper.rb:495:in `rails_context'
     # /var/lib/gems/2.3.0/gems/react_on_rails-10.0.2/app/helpers/react_on_rails_helper.rb:321:in `prepend_render_rails_context'
     # /var/lib/gems/2.3.0/gems/react_on_rails-10.0.2/app/helpers/react_on_rails_helper.rb:269:in `build_react_component_result_for_server_rendered_string'
     # /var/lib/gems/2.3.0/gems/react_on_rails-10.0.2/app/helpers/react_on_rails_helper.rb:105:in `react_component'
     # ./app/views/controls/_snippet.html.haml:228:in `_app_views_controls__snippet_html_haml__746596864835777334_253774320'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/template.rb:157:in `block in render'
     # /var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `block in instrument'
     # /var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
     # /var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `instrument'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/template.rb:352:in `instrument_render_template'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/template.rb:155:in `render'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/partial_renderer.rb:342:in `block in render_partial'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
     # /var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `block in instrument'
     # /var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
     # /var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `instrument'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/partial_renderer.rb:331:in `render_partial'
     # /var/lib/gems/2.3.0/gems/ddtrace-0.11.4/lib/ddtrace/contrib/rails/core_extensions.rb:122:in `render_partial_with_datadog'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/partial_renderer.rb:310:in `render'
     # /var/lib/gems/2.3.0/gems/ddtrace-0.11.4/lib/ddtrace/contrib/rails/core_extensions.rb:98:in `render_with_datadog'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/renderer.rb:47:in `render_partial'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/helpers/rendering_helper.rb:35:in `render'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/test_case.rb:203:in `render'
     # ./app/views/controls/show.html.haml:131:in `_app_views_controls_show_html_haml__1460547735093567258_271711160'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/template.rb:157:in `block in render'
     # /var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `block in instrument'
     # /var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
     # /var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `instrument'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/template.rb:352:in `instrument_render_template'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/template.rb:155:in `render'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/template_renderer.rb:52:in `block (2 levels) in render_template'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
     # /var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `block in instrument'
     # /var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
     # /var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `instrument'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/template_renderer.rb:51:in `block in render_template'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/template_renderer.rb:59:in `render_with_layout'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/template_renderer.rb:50:in `render_template'
     # /var/lib/gems/2.3.0/gems/ddtrace-0.11.4/lib/ddtrace/contrib/rails/core_extensions.rb:70:in `render_template_with_datadog'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/template_renderer.rb:14:in `render'
     # /var/lib/gems/2.3.0/gems/ddtrace-0.11.4/lib/ddtrace/contrib/rails/core_extensions.rb:38:in `render_with_datadog'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/renderer.rb:42:in `render_template'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/renderer.rb:23:in `render'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/helpers/rendering_helper.rb:32:in `render'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/test_case.rb:203:in `render'
     # /var/lib/gems/2.3.0/gems/actionview-5.1.6/lib/action_view/test_case.rb:119:in `render'
     # ./spec/views/controls/show.haml.haml_spec.rb:129:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Addressable::URI::InvalidURIError:
     #   Invalid port number: "controller=>\"controls\"}"
     #   /var/lib/gems/2.3.0/gems/addressable-2.5.2/lib/addressable/uri.rb:1373:in `port='

```

**Comment by mechabyte** [comment]
Capybara is configured as follows inside `spec_helper`:

```ruby
Capybara.javascript_driver = :webkit

Capybara::Webkit.configure do |config|
  config.block_unknown_urls
  config.allow_url("cdnjs.cloudflare.com")
  config.allow_url("maps.googleapis.com")
  config.skip_image_loading
end


# Config Rspec
RSpec.configure do |config|
  config.alias_example_to :with

  config.mock_with :rspec do |configuration|
    configuration.syntax = [:expect, :should]
  end

  config.fixture_path = "#{::Rails.root}/spec/fixtures"
  config.include Paperclip::Shoulda::Matchers
  config.include Requests::JsonHelpers, :type => :controller
  config.include Devise::Test::ControllerHelpers, type: :controller
  config.include Devise::Test::ControllerHelpers, :type => :view
  config.include Warden::Test::Helpers, type: :feature # Devise Helpers in feature requests
  config.use_transactional_fixtures = false
  config.raise_errors_for_deprecations!

  config.extend Requests::DeviseHelpers, :type => :controller

  config.before(:suite) do
    DatabaseCleaner.clean_with(:truncation)
    ApiKey.create!(id: 1) unless ApiKey.where(id: 1).any?
    load "#{Rails.root}/db/subscription_plan_seed.rb"
  end

  config.before(:each) do
    DatabaseCleaner.strategy = :transaction
    Sidekiq::Worker.clear_all
    Rails.logger.info ' ------------- '
  end

  config.before(:each, :js => true) do
    DatabaseCleaner.strategy = :deletion
    Rails.logger.info ' ------------- '
  end

  config.before(:each) do
    DatabaseCleaner.start
  end

  config.after(:each) do
    DatabaseCleaner.clean
  end

  config.after(:all) do
    if Rails.env.test?
      FileUtils.rm_rf(Dir["#{Rails.root}/test"])
      FileUtils.rm_rf(Dir["#{Rails.root}/test-modem_versions"])
    end
  end
end
```

**Comment by justin808** [comment]
@mechabyte I can with certainty that the issues you are having are due to the library React on Rails. That being said, I'd love to help you more.

1. Check out the test setup of https://github.com/shakacode/react-webpack-rails-tutorial.
2. Would you be interested in our ShakaCode Pro Support plan? 

http://www.shakacode.com/work/shakacode-pro-support.pdf

If so, please schedule a complimentary 30-minute consultation:
https://calendly.com/justingordon

Thanks,

Justin
justin@shakacode.com

**Comment by mechabyte** [comment]
@justin808 I'll take a look through the tutorial again to see if I glossed over anything that could be causing this issue. If that doesn't solve it, I can consult with my coworkers to see what they'd like to do as far as a support plan. Thanks for your help & continued work on this library.
