### ISSUE TITLE
SSR Styled Componenets Giving Unitialized Constant Error

### ISSUE THREAD

**Issue by juliusdelta** [shakacode/react_on_rails#1110]
We're using server side rendering along with [Styled Components](https://www.styled-components.com/). We've ran into an issue and would just like clarification on whether or not we've hit the need for the ReactOnRailsPro functionality.

```jsx
// client/startup/withStyledSsr.jsx
import React from 'react';
import { renderToString } from 'react-dom/server';
import { ServerStyleSheet } from 'styled-components';

export default function (Component) {
  return (props, railsContext) => {
    const sheet = new ServerStyleSheet();
    const html = renderToString(sheet.collectStyles(<Component {...props} railsContext={railsContext} />));
    const css = sheet.getStyleTags();
    return { renderedHtml: { componentHtml: html, componentCss: css } };
  };
}
```

```javascript
// serverRegistration.js <= server rendered entry point for webpack
ReactOnRails.register({
  Profile: withStyledSsr(Profile)
});
```

```erb
<!-- app/views/rewards/profile.html.erb -->
<% profile = react_component("Profile", props: {}, prerender: true) %>
<%= profile["componentHtml"] %>
<%= profile["componentCss"] %>
```

The error we get at this point is:
```
NameError - uninitialized constant ReactOnRails::Helper::ReactOnRailsPro:
app/views/rewards/profile.html.erb:4:in `_app_views_rewards_profile_html_erb__7308808005276661_70269248777580'
app/controllers/rewards_controller.rb:41:in `profile'
config/initializers/rack_mini_profiler.rb:13:in `call'
```

**Comment by juliusdelta** [comment]
It actually seems we were using `react_component` instead of `react_component_hash`. So I'm closing for now.

I would like to say how appreciative I am for this library and the documentation. 👍
