### ISSUE TITLE
Runing generator fail.

### ISSUE THREAD

**Issue by DimaZab** [shakacode/react_on_rails#197]
```
       route  get 'hello_world', to: 'hello_world#index'
      create  client/assets
      create  client/assets/stylesheets
      create  client/assets/fonts
      create  client/assets/fonts/.keep
      create  client/assets/images
      create  client/assets/images/.keep
      append  .gitignore
      create  app/assets/javascripts/application.js
        gsub  app/assets/javascripts/application.js
        gsub  app/assets/javascripts/application.js
        gsub  app/assets/javascripts/application.js
        gsub  app/assets/javascripts/application.js
      create  client/app/bundles/HelloWorld/components
      create  client/app/bundles/HelloWorld/containers
      create  client/app/bundles/HelloWorld/startup
      create  app/controllers/hello_world_controller.rb
      create  config/initializers/react_on_rails.rb
      create  client/.babelrc
      create  client/index.jade
      create  client/server.js
      create  client/webpack.client.base.config.js
      create  client/webpack.client.rails.config.js
      create  REACT_ON_RAILS.md
      create  client/REACT_ON_RAILS_CLIENT_README.md
      create  package.json
      create  Procfile.dev
      create  Procfile.dev-hot
      create  app/views/hello_world/index.html.erb
      create  client/app/bundles/HelloWorld/components/HelloWorldWidget.jsx
      create  client/webpack.client.hot.config.js
      create  client/package.json
(erb):67:in `template': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/2.3.0/erb.rb:864:in `eval'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/2.3.0/erb.rb:864:in `result'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:116:in `block in template'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `render'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `block (2 levels) in invoke!'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `open'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `block in invoke!'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in `invoke_with_conflict_check'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:60:in `invoke!'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:25:in `create_file'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:115:in `template'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/react_on_rails-2.0.0/lib/generators/react_on_rails/base_generator.rb:132:in `block in template_base_files'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/react_on_rails-2.0.0/lib/generators/react_on_rails/base_generator.rb:132:in `each'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/react_on_rails-2.0.0/lib/generators/react_on_rails/base_generator.rb:132:in `template_base_files'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/react_on_rails-2.0.0/lib/generators/react_on_rails/install_generator.rb:77:in `invoke_generators'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/react_on_rails-2.0.0/lib/generators/react_on_rails/install_generator.rb:58:in `run_generators'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.4/lib/rails/generators.rb:157:in `invoke'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.4/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/dima/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by robwise** [comment]
Should be addressed by a hotfix in https://github.com/shakacode/react_on_rails/pull/201
