### ISSUE TITLE
Can't foreman start. (webpack: Permission denied)

### ISSUE THREAD

**Issue by TSMMark** [shakacode/react_on_rails#389]
I am trying to add react_on_rails to a project which was using react-rails. I have run the `react_on_rails:install` generator and run `bundle install` and `npm install`. I am using rbenv and vagrant if that makes a difference.

Here is what happens when I try to foreman s

```
vagrant$ foreman start -f Procfile.dev
21:10:19 web.1    | started with pid 24083
21:10:19 client.1 | started with pid 24084
21:10:19 server.1 | started with pid 24085
21:10:19 client.1 | rm: cannot remove ‘app/assets/webpack/*’: No such file or directory
21:10:20 server.1 | 
21:10:20 server.1 | > react-webpack-rails-tutorial@0.0.1 build:dev:server /home/vagrant/pwnagon/client
21:10:20 server.1 | > webpack -w --config webpack.server.rails.config.js
21:10:20 server.1 | 
21:10:20 server.1 | sh: 1: webpack: Permission denied
21:10:20 server.1 | 
21:10:20 server.1 | npm ERR! Linux 3.13.0-51-generic
21:10:20 server.1 | npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "run" "build:dev:server"
21:10:20 server.1 | npm ERR! node v5.10.1
21:10:20 server.1 | npm ERR! npm  v3.8.6
21:10:20 server.1 | npm ERR! code ELIFECYCLE
21:10:20 server.1 | npm ERR! react-webpack-rails-tutorial@0.0.1 build:dev:server: `webpack -w --config webpack.server.rails.config.js`
21:10:20 server.1 | npm ERR! Exit status 126
21:10:20 server.1 | npm ERR! 
21:10:20 server.1 | npm ERR! Failed at the react-webpack-rails-tutorial@0.0.1 build:dev:server script 'webpack -w --config webpack.server.rails.config.js'.
21:10:20 server.1 | npm ERR! Make sure you have the latest version of node.js and npm installed.
21:10:20 server.1 | npm ERR! If you do, this is most likely a problem with the react-webpack-rails-tutorial package,
21:10:20 server.1 | npm ERR! not with npm itself.
21:10:20 server.1 | npm ERR! Tell the author that this fails on your system:
21:10:20 server.1 | npm ERR!     webpack -w --config webpack.server.rails.config.js
21:10:20 server.1 | npm ERR! You can get information on how to open an issue for this project with:
21:10:20 server.1 | npm ERR!     npm bugs react-webpack-rails-tutorial
21:10:20 server.1 | npm ERR! Or if that isn't available, you can get their info via:
21:10:20 server.1 | npm ERR!     npm owner ls react-webpack-rails-tutorial
21:10:20 server.1 | npm ERR! There is likely additional logging output above.
21:10:20 server.1 | 
21:10:20 server.1 | npm ERR! Please include the following file with any support request:
21:10:20 server.1 | npm ERR!     /home/vagrant/pwnagon/client/npm-debug.log
21:10:20 server.1 | exited with code 1
21:10:20 system   | sending SIGTERM to all processes
21:10:20 client.1 | terminated by SIGTERM
21:10:20          | 
21:10:20          | > react-webpack-rails-tutorial@0.0.1 build:dev:client /home/vagrant/pwnagon/client
21:10:20          | > webpack -w --config webpack.client.rails.config.js
21:10:20          | 
21:10:20 web.1    | terminated by SIGTERM
```

More details:

```
vagrant$ npm -v
3.8.3
vagrant$ node -v
v5.10.1
```

```
vagrant$ cat /home/vagrant/pwnagon/client/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:dev:server' ]
2 info using npm@3.8.6
3 info using node@v5.10.1
4 verbose run-script [ 'prebuild:dev:server',
4 verbose run-script   'build:dev:server',
4 verbose run-script   'postbuild:dev:server' ]
5 info lifecycle react-webpack-rails-tutorial@0.0.1~prebuild:dev:server: react-webpack-rails-tutorial@0.0.1
6 silly lifecycle react-webpack-rails-tutorial@0.0.1~prebuild:dev:server: no script for prebuild:dev:server, continuing
7 info lifecycle react-webpack-rails-tutorial@0.0.1~build:dev:server: react-webpack-rails-tutorial@0.0.1
8 verbose lifecycle react-webpack-rails-tutorial@0.0.1~build:dev:server: unsafe-perm in lifecycle true
9 verbose lifecycle react-webpack-rails-tutorial@0.0.1~build:dev:server: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/vagrant/pwnagon/client/node_modules/.bin:/usr/bin:/home/vagrant/.rbenv/versions/2.2.4/bin:/home/vagrant/.rbenv/libexec:/home/vagrant/.rbenv/plugins/ruby-build/bin:/home/vagrant/.rbenv/shims:/home/vagrant/.rbenv/bin:/usr/local:/usr/local/sbin:~/bin:/usr/local/heroku/bin:/usr/local/bin:/home/vagrant/bin:/home/vagrant/.rbenv/bin:/home/vagrant/.rbenv/shims:/usr/local:/usr/local/sbin:~/bin:/usr/local/heroku/bin:/usr/local/bin:/home/vagrant/bin:/home/vagrant/.rbenv/bin:/usr/local:/usr/local/sbin:~/bin:/usr/local/heroku/bin:/usr/local/bin:/home/vagrant/bin:/home/vagrant/.rbenv/shims:/usr/local:/usr/local/sbin:~/bin:/usr/local/heroku/bin:/usr/local/bin:/home/vagrant/bin:/usr/local:/usr/local/sbin:~/bin:/usr/local/heroku/bin:/usr/local/bin:/home/vagrant/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle react-webpack-rails-tutorial@0.0.1~build:dev:server: CWD: /home/vagrant/pwnagon/client
11 silly lifecycle react-webpack-rails-tutorial@0.0.1~build:dev:server: Args: [ '-c', 'webpack -w --config webpack.server.rails.config.js' ]
12 silly lifecycle react-webpack-rails-tutorial@0.0.1~build:dev:server: Returned: code: 126  signal: null
13 info lifecycle react-webpack-rails-tutorial@0.0.1~build:dev:server: Failed to exec build:dev:server script
14 verbose stack Error: react-webpack-rails-tutorial@0.0.1 build:dev:server: `webpack -w --config webpack.server.rails.config.js`
14 verbose stack Exit status 126
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid react-webpack-rails-tutorial@0.0.1
16 verbose cwd /home/vagrant/pwnagon/client
17 error Linux 3.13.0-51-generic
18 error argv "/usr/bin/nodejs" "/usr/local/bin/npm" "run" "build:dev:server"
19 error node v5.10.1
20 error npm  v3.8.6
21 error code ELIFECYCLE
22 error react-webpack-rails-tutorial@0.0.1 build:dev:server: `webpack -w --config webpack.server.rails.config.js`
22 error Exit status 126
23 error Failed at the react-webpack-rails-tutorial@0.0.1 build:dev:server script 'webpack -w --config webpack.server.rails.config.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-webpack-rails-tutorial package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack -w --config webpack.server.rails.config.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-webpack-rails-tutorial
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-webpack-rails-tutorial
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

```
vagrant$ npm i

> react-webpack-rails-tutorial@0.0.1 postinstall /home/vagrant/pwnagon
> cd client && npm install

npm WARN optional Skipping failed optional dependency /babel-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm WARN optional Skipping failed optional dependency /webpack/watchpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm WARN react-webpack-rails-tutorial@0.0.1 No description
npm WARN react-webpack-rails-tutorial@0.0.1 No repository field.
npm WARN react-webpack-rails-tutorial@0.0.1 No license field.
npm WARN react-webpack-rails-tutorial@0.0.1 No repository field.
npm WARN react-webpack-rails-tutorial@0.0.1 No license field.
```

**Comment by justin808** [comment]
@TSMMark I recommend using nvm to manage node. 

The error is that webpack is not in the path or there is a permission problem.

21:10:20 server.1 | > webpack -w --config webpack.server.rails.config.js
21:10:20 server.1 | 
21:10:20 server.1 | sh: 1: webpack: Permission denied
