### ISSUE TITLE
No such file or directory @ rb_file_s_mtime

### ISSUE THREAD

**Issue by marcohk** [shakacode/react_on_rails#400]
I got this error when running the auto-generated hello world with `foreman start -f Procfile.dev` and accessing the `/hello_world` on browser:

```
ActionView::Template::Error (No such file or directory @ rb_file_s_mtime - app/assets/webpack/server-bundle.js):
    1: <h1 class="alert alert-info this-works">Server Rendering</h1>
    2: <%= react_component("HelloWorldApp",
    3:                      props: @hello_world_props,
    4:                      prerender: true) %>

app/views/hello_world/index.html.erb:2:in `_app_views_hello_world_index_html_erb___4400523833287329603_70102157165740'
  Rendered /Users/marcohk/.rvm/gems/ruby-2.3.0-latest/gems/actionpack-5.0.0.beta3/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (8.7ms)
  Rendered /Users/marcohk/.rvm/gems/ruby-2.3.0-latest/gems/actionpack-5.0.0.beta3/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.7ms)
  Rendered /Users/marcohk/.rvm/gems/ruby-2.3.0-latest/gems/actionpack-5.0.0.beta3/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (3.0ms)
  Rendered /Users/marcohk/.rvm/gems/ruby-2.3.0-latest/gems/actionpack-5.0.0.beta3/lib/action_dispatch/middleware/templates/rescues/template_error.html.erb within rescues/layout (127.7ms)
  Rendered /Users/marcohk/.rvm/gems/ruby-2.3.0-latest/gems/web-console-3.1.1/lib/web_console/templates/_markup.html.erb (0.7ms)
  Rendered /Users/marcohk/.rvm/gems/ruby-2.3.0-latest/gems/web-console-3.1.1/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.5ms)
  Rendered /Users/marcohk/.rvm/gems/ruby-2.3.0-latest/gems/web-console-3.1.1/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.4ms)
  Rendered /Users/marcohk/.rvm/gems/ruby-2.3.0-latest/gems/web-console-3.1.1/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.5ms)
  Rendered /Users/marcohk/.rvm/gems/ruby-2.3.0-latest/gems/web-console-3.1.1/lib/web_console/templates/console.js.erb within layouts/javascript (169.3ms)
  Rendered /Users/marcohk/.rvm/gems/ruby-2.3.0-latest/gems/web-console-3.1.1/lib/web_console/templates/main.js.erb within layouts/javascript (2.8ms)
  Rendered /Users/marcohk/.rvm/gems/ruby-2.3.0-latest/gems/web-console-3.1.1/lib/web_console/templates/index.html.erb (301.1ms)
```

Gemfile.lock:
```
...

    rails (5.0.0.beta3)
      actioncable (= 5.0.0.beta3)
      actionmailer (= 5.0.0.beta3)
      actionpack (= 5.0.0.beta3)
      actionview (= 5.0.0.beta3)
      activejob (= 5.0.0.beta3)
      activemodel (= 5.0.0.beta3)
      activerecord (= 5.0.0.beta3)
      activesupport (= 5.0.0.beta3)
      bundler (>= 1.3.0, < 2.0)
      railties (= 5.0.0.beta3)
      sprockets-rails (>= 2.0.0)

    react_on_rails (5.2.0)
      connection_pool
      execjs (~> 2.5)
      foreman
      rails (>= 3.2)
      rainbow (~> 2.1)

...
```

The hello world was auto generated by `rails generate react_on_rails:install -R -S`
Does anyone know if I did something wrong?

**Comment by marcohk** [comment]
Below is the complete backtrace:
```
react_on_rails (5.2.0) lib/react_on_rails/server_rendering_pool.rb:16:in `mtime'
react_on_rails (5.2.0) lib/react_on_rails/server_rendering_pool.rb:16:in `reset_pool_if_server_bundle_was_modified'
react_on_rails (5.2.0) app/helpers/react_on_rails_helper.rb:294:in `server_rendered_react_component_html'
react_on_rails (5.2.0) app/helpers/react_on_rails_helper.rb:135:in `react_component'
app/views/hello_world/index.html.erb:2:in `_app_views_hello_world_index_html_erb___3824419487914948469_70147901349100'
actionview (5.0.0.beta3) lib/action_view/template.rb:158:in `block in render'
activesupport (5.0.0.beta3) lib/active_support/notifications.rb:166:in `instrument'
actionview (5.0.0.beta3) lib/action_view/template.rb:348:in `instrument'
actionview (5.0.0.beta3) lib/action_view/template.rb:156:in `render'
actionview (5.0.0.beta3) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
actionview (5.0.0.beta3) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
activesupport (5.0.0.beta3) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.0.beta3) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.0.beta3) lib/active_support/notifications.rb:164:in `instrument'
actionview (5.0.0.beta3) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
actionview (5.0.0.beta3) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
actionview (5.0.0.beta3) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
actionview (5.0.0.beta3) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (5.0.0.beta3) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (5.0.0.beta3) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (5.0.0.beta3) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.0.0.beta3) lib/action_view/rendering.rb:103:in `_render_template'
actionpack (5.0.0.beta3) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (5.0.0.beta3) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (5.0.0.beta3) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.0.0.beta3) lib/action_controller/metal/renderers.rb:144:in `render_to_body'
actionpack (5.0.0.beta3) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (5.0.0.beta3) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.0.0.beta3) lib/action_controller/metal/instrumentation.rb:43:in `block (2 levels) in render'
activesupport (5.0.0.beta3) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/marcohk/.rvm/rubies/ruby-2.3.0-latest/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
activesupport (5.0.0.beta3) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (5.0.0.beta3) lib/action_controller/metal/instrumentation.rb:43:in `block in render'
actionpack (5.0.0.beta3) lib/action_controller/metal/instrumentation.rb:86:in `cleanup_view_runtime'
activerecord (5.0.0.beta3) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (5.0.0.beta3) lib/action_controller/metal/instrumentation.rb:42:in `render'
actionpack (5.0.0.beta3) lib/action_controller/metal/implicit_render.rb:19:in `default_render'
actionpack (5.0.0.beta3) lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
actionpack (5.0.0.beta3) lib/action_controller/metal/basic_implicit_render.rb:4:in `tap'
actionpack (5.0.0.beta3) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.0.beta3) lib/abstract_controller/base.rb:183:in `process_action'
actionpack (5.0.0.beta3) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.0.beta3) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.0.beta3) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.0.beta3) lib/action_controller/metal/rescue.rb:27:in `process_action'
actionpack (5.0.0.beta3) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (5.0.0.beta3) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.0.beta3) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.0.beta3) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.0.beta3) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (5.0.0.beta3) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.0.beta3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (5.0.0.beta3) lib/abstract_controller/base.rb:128:in `process'
actionview (5.0.0.beta3) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.0.beta3) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.0.beta3) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.0.beta3) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.0.beta3) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.0.beta3) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.0.beta3) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.0.beta3) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.0.beta3) lib/action_dispatch/routing/route_set.rb:724:in `call'
actionview (5.0.0.beta3) lib/action_view/digestor.rb:12:in `call'
warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
warden (1.2.6) lib/warden/manager.rb:34:in `catch'
warden (1.2.6) lib/warden/manager.rb:34:in `call'
rack (2.0.0.alpha) lib/rack/etag.rb:25:in `call'
rack (2.0.0.alpha) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.0.alpha) lib/rack/head.rb:12:in `call'
rack (2.0.0.alpha) lib/rack/session/abstract/id.rb:220:in `context'
rack (2.0.0.alpha) lib/rack/session/abstract/id.rb:214:in `call'
actionpack (5.0.0.beta3) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.0.0.beta3) lib/active_record/query_cache.rb:36:in `call'
activerecord (5.0.0.beta3) lib/active_record/connection_adapters/abstract/connection_pool.rb:963:in `call'
activerecord (5.0.0.beta3) lib/active_record/migration.rb:558:in `call'
actionpack (5.0.0.beta3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.0.beta3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (5.0.0.beta3) lib/action_dispatch/middleware/reloader.rb:71:in `call'
actionpack (5.0.0.beta3) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.0.beta3) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
web-console (3.1.1) lib/web_console/middleware.rb:131:in `call_app'
web-console (3.1.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.1.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.1.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.0.0.beta3) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.0.beta3) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.0.beta3) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.0.beta3) lib/active_support/tagged_logging.rb:70:in `block in tagged'
activesupport (5.0.0.beta3) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.0.beta3) lib/active_support/tagged_logging.rb:70:in `tagged'
railties (5.0.0.beta3) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.0.beta3) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.0.alpha) lib/rack/method_override.rb:22:in `call'
rack (2.0.0.alpha) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.0.beta3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.0.beta3) lib/action_dispatch/middleware/load_interlock.rb:13:in `call'
actionpack (5.0.0.beta3) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.0.alpha) lib/rack/sendfile.rb:111:in `call'
railties (5.0.0.beta3) lib/rails/engine.rb:522:in `call'
puma (3.4.0) lib/puma/configuration.rb:224:in `call'
puma (3.4.0) lib/puma/server.rb:569:in `handle_request'
puma (3.4.0) lib/puma/server.rb:406:in `process_client'
puma (3.4.0) lib/puma/server.rb:271:in `block in run'
puma (3.4.0) lib/puma/thread_pool.rb:114:in `block in spawn_thread'
```

**Comment by marcohk** [comment]
I was trying to start the server by `foreman` instead of `rails`, but resulted in the following errors:
```
/Users/marcohk/.rvm/gems/ruby-2.3.0-latest/gems/foreman-0.80.1/lib/foreman/engine.rb:442:in `check_for_termination': undefined method `exitstatus' for nil:NilClass (NoMethodError)
	from /Users/marcohk/.rvm/gems/ruby-2.3.0-latest/gems/foreman-0.80.1/lib/foreman/engine.rb:420:in `block in wait_for_shutdown_or_child_termination'
	from /Users/marcohk/.rvm/gems/ruby-2.3.0-latest/gems/foreman-0.80.1/lib/foreman/engine.rb:415:in `loop'
	from /Users/marcohk/.rvm/gems/ruby-2.3.0-latest/gems/foreman-0.80.1/lib/foreman/engine.rb:415:in `wait_for_shutdown_or_child_termination'
	from /Users/marcohk/.rvm/gems/ruby-2.3.0-latest/gems/foreman-0.80.1/lib/foreman/engine.rb:60:in `start'
	from /Users/marcohk/.rvm/gems/ruby-2.3.0-latest/gems/foreman-0.80.1/lib/foreman/cli.rb:41:in `start'
	from /Users/marcohk/.rvm/gems/ruby-2.3.0-latest/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/marcohk/.rvm/gems/ruby-2.3.0-latest/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/marcohk/.rvm/gems/ruby-2.3.0-latest/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/marcohk/.rvm/gems/ruby-2.3.0-latest/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/marcohk/.rvm/gems/ruby-2.3.0-latest/gems/foreman-0.80.1/bin/foreman:7:in `<top (required)>'
	from /Users/marcohk/.rvm/gems/ruby-2.3.0-latest/bin/foreman:23:in `load'
	from /Users/marcohk/.rvm/gems/ruby-2.3.0-latest/bin/foreman:23:in `<main>'
	from /Users/marcohk/.rvm/gems/ruby-2.3.0-latest/bin/ruby_executable_hooks:15:in `eval'
	from /Users/marcohk/.rvm/gems/ruby-2.3.0-latest/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by marcohk** [comment]
Although I am very sure I have run `npm install` already.
I solved it by running `npm install` again.

**Comment by matthewrobb** [comment]
I am seeing this and rerunning npm install didn't seem to help.

**Comment by koryteg** [comment]
I am seeing this as well.. my error looks more like this though: 
`No such file or directory @ rb_file_s_mtime - app/assets/webpack/server-bundle.js`

**Comment by pmaojo** [comment]
I had the same issue. The " ' " on You're is a problem, and a div is not closed:

`import React, { PropTypes } from 'react';

import BaseComponent from 'libs/components/BaseComponent';

import CommentBox from '../CommentBox/CommentBox';
import css from './CommentScreen.scss';

export default class CommentScreen extends BaseComponent {

  static propTypes = {
    actions: PropTypes.object.isRequired,
    data: PropTypes.object.isRequired,
    locationState: PropTypes.object,
  };

  renderNotification() {
    const { locationState } = this.props;

    if (!locationState || !locationState.redirectFrom) return null;

    return (
      <div className={`bg-success ${css.notification}`}>
        U been redirected from <strong>{locationState.redirectFrom}</strong>
      </div> );
  }

  render() {
    const { data, actions } = this.props;

    return (
      <div>
        {this.renderNotification()}
        <div>
          <CommentBox
            pollInterval={60000}
            data={data}
            actions={actions}
            ajaxCounter={data.get('ajaxCounter')}   />
        </div>
      </div>
    );
  }
}
`
