### ISSUE TITLE
Test failures on forked version of master (not CI)

### ISSUE THREAD

**Issue by tompave-roo** [shakacode/react_on_rails#427]
Hi, I've forked the repo, followed the setup guide, and now I'm trying to run the tests locally.

I'm getting three failures that might have to do with my local setup. Do you have any pointers?

I'm running the rests with `rake` in the root directory, on master at `c805508a`.
My local setup is:

* OS X 10.11.5
* Ruby MRI 2.2.3
* node 6.2.0
* npm 3.8.9

Thank you for the help.

```
  1) 2 react components, 1 store, server side /server_side_hello_world_shared_store Type in one component changes the other component
     Failure/Error: background { visit url }

     Capybara::Poltergeist::DeadClient:
       PhantomJS client died while processing {"id":"0164486d-2dae-473b-9bd3-05bc100123a8","name":"visit","args":["http://127.0.0.1:57426/server_side_hello_world_shared_store",30]}
     Shared Example Group: "React Component Shared Store" called from ./spec/features/integration_spec.rb:180
     # /Users/tom/.rvm/gems/ruby-2.2.3/gems/poltergeist-1.9.0/lib/capybara/poltergeist/server.rb:38:in `send'
     # /Users/tom/.rvm/gems/ruby-2.2.3/gems/poltergeist-1.9.0/lib/capybara/poltergeist/browser.rb:344:in `command'
     # /Users/tom/.rvm/gems/ruby-2.2.3/gems/poltergeist-1.9.0/lib/capybara/poltergeist/browser.rb:34:in `visit'
     # /Users/tom/.rvm/gems/ruby-2.2.3/gems/poltergeist-1.9.0/lib/capybara/poltergeist/driver.rb:95:in `visit'
     # /Users/tom/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.1/lib/capybara/session.rb:233:in `visit'
     # /Users/tom/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
     # ./spec/features/integration_spec.rb:148:in `block (2 levels) in <top (required)>'

  2) 2 react components, 1 store, client only, defer /client_side_hello_world_shared_store_defer Type in one component changes the other component
     Failure/Error: background { visit url }

     Capybara::Poltergeist::DeadClient:
       PhantomJS client died while processing {"id":"22783fda-c801-41bc-8c75-43e8d6704e07","name":"visit","args":["http://127.0.0.1:57426/client_side_hello_world_shared_store_defer",30]}
     Shared Example Group: "React Component Shared Store" called from ./spec/features/integration_spec.rb:192
     # /Users/tom/.rvm/gems/ruby-2.2.3/gems/poltergeist-1.9.0/lib/capybara/poltergeist/server.rb:38:in `send'
     # /Users/tom/.rvm/gems/ruby-2.2.3/gems/poltergeist-1.9.0/lib/capybara/poltergeist/browser.rb:344:in `command'
     # /Users/tom/.rvm/gems/ruby-2.2.3/gems/poltergeist-1.9.0/lib/capybara/poltergeist/browser.rb:34:in `visit'
     # /Users/tom/.rvm/gems/ruby-2.2.3/gems/poltergeist-1.9.0/lib/capybara/poltergeist/driver.rb:95:in `visit'
     # /Users/tom/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.1/lib/capybara/session.rb:233:in `visit'
     # /Users/tom/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
     # ./spec/features/integration_spec.rb:148:in `block (2 levels) in <top (required)>'

  3) rails_context server rendering shared store server_side_hello_world_shared_store check rails context
     Failure/Error: visit "/#{pathname}?ab=cd"

     Capybara::Poltergeist::DeadClient:
       PhantomJS client died while processing {"id":"64abeb87-8382-4f26-bd7d-e245484b5a6b","name":"visit","args":["http://127.0.0.1:57426/server_side_hello_world_shared_store?ab=cd",30]}
     Shared Example Group: "railsContext" called from ./spec/features/rails_context_spec.rb:59
     # /Users/tom/.rvm/gems/ruby-2.2.3/gems/poltergeist-1.9.0/lib/capybara/poltergeist/server.rb:38:in `send'
     # /Users/tom/.rvm/gems/ruby-2.2.3/gems/poltergeist-1.9.0/lib/capybara/poltergeist/browser.rb:344:in `command'
     # /Users/tom/.rvm/gems/ruby-2.2.3/gems/poltergeist-1.9.0/lib/capybara/poltergeist/browser.rb:34:in `visit'
     # /Users/tom/.rvm/gems/ruby-2.2.3/gems/poltergeist-1.9.0/lib/capybara/poltergeist/driver.rb:95:in `visit'
     # /Users/tom/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.1/lib/capybara/session.rb:233:in `visit'
     # /Users/tom/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
     # ./spec/features/rails_context_spec.rb:13:in `block (2 levels) in <top (required)>'
```

**Comment by justin808** [comment]
@tompave-roo Please read the error messages carefully. It seems that you have Poltergeist setup issues. What version of phantomjs do you have installed?

**Comment by justin808** [comment]
@tompave-roo Please ask me to re-open this issue if you think it's a problem with the code, versus your environment.
