### ISSUE TITLE
Error with npm run rails-server

### ISSUE THREAD

**Issue by alagos** [shakacode/react_on_rails#441]
I'm using react_on_rails (6.0.1) and after run `rails generate react_on_rails:install` I followed the given instructions:
```
What to do next:                                                                                                                      

  - Ensure your bundle and npm are up to date.                                                                                        

      bundle && npm i                                                                                                                 

  - Run the npm rails-server command to load the rails server.                                                                        

      npm run rails-server                                                                                                            

  - Visit http://localhost:3000/hello_world and see your React On Rails app running!                                                  
```
But when I run `npm run rails-server` it throws:
```shell
 ➜ npm run rails-server

> react-webpack-rails-tutorial@0.0.1 rails-server /files/alter/workspace/members
> echo 'visit http://localhost:3000/hello_world' && foreman start -f Procfile.dev

visit http://localhost:3000/hello_world
/home/alter/.rvm/gems/ruby-2.3.1@5.0.0/gems/bundler-1.11.2/lib/bundler/definition.rb:402:in `validate_ruby!': Your Ruby version is 1.9.3, but your Gemfile specified 2.3.1 (Bundler::RubyVersionMismatch)
        from /home/alter/.rvm/gems/ruby-2.3.1@5.0.0/gems/bundler-1.11.2/lib/bundler.rb:88:in `setup'
        from /home/alter/.rvm/gems/ruby-2.3.1@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:94:in `setup'
        from /home/alter/.rvm/gems/ruby-2.3.1@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:124:in `check'
        from /home/alter/.rvm/gems/ruby-2.3.1@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:131:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
        from /home/alter/.rvm/gems/ruby-2.3.1@global/gems/rubygems-bundler-1.4.4/lib/rubygems_executable_plugin.rb:4:in `block in <top (required)>'
        from /home/alter/.rvm/gems/ruby-2.3.1@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hooks.rb:50:in `call'
        from /home/alter/.rvm/gems/ruby-2.3.1@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hooks.rb:50:in `block in run'
        from /home/alter/.rvm/gems/ruby-2.3.1@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hooks.rb:49:in `each'
        from /home/alter/.rvm/gems/ruby-2.3.1@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hooks.rb:49:in `run'
        from /home/alter/.rvm/gems/ruby-2.3.1@5.0.0/bin/ruby_executable_hooks:10:in `<main>'

npm ERR! react-webpack-rails-tutorial@0.0.1 rails-server: `echo 'visit http://localhost:3000/hello_world' && foreman start -f Procfile.dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-webpack-rails-tutorial@0.0.1 rails-server script.
npm ERR! This is most likely a problem with the react-webpack-rails-tutorial package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     echo 'visit http://localhost:3000/hello_world' && foreman start -f Procfile.dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-webpack-rails-tutorial
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "node" "/home/alter/npm/bin/npm" "run" "rails-server"
npm ERR! cwd /files/alter/workspace/members
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.20
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /files/alter/workspace/members/npm-debug.log
npm ERR! not ok code 0
```

Not sure if the error has to do with npm using rvm as is trying to use a 1.9.3 ruby version.
BTW, those `rails generate react_on_rails:install` instructions are different than the described on the [Getting Started](https://github.com/shakacode/react_on_rails#getting-started) section, where with `foreman start -f Procfile.dev`, the app run successfully.

**Comment by justin808** [comment]
The error message is clear.

run `rvm-prompt` before starting the command and verify that you have 2.3.1 properly set.



> echo 'visit http://localhost:3000/hello_world' && foreman start -f Procfile.dev
visit http://localhost:3000/hello_world
/home/alter/.rvm/gems/ruby-2.3.1@5.0.0/gems/bundler-1.11.2/lib/bundler/definition.rb:402:in `validate_ruby!': Your Ruby version is 1.9.3, but your Gemfile specified 2.3.1 (Bundler::RubyVersionMismatch)

**Comment by alagos** [comment]
@justin808 I have properly set my rvm version
```
➜ rvm-prompt
ruby-2.3.1@5.0.0
```
Also the error line indicates the error comes from bundler located in `.rvm/gems/ruby-2.3.1@5.0.0/gems/bundler-1.11.2`, which corresponds to 2.3.1 version. And last but not least, I don't have problems to run the application with `foreman start -f Procfile.dev`, which would fail if my rvm had an incorrect version, it just fails with `npm run rails-server`.

**Comment by justin808** [comment]
@alagos @jbhatab We should consider taking out the npm task from the generator.

**Comment by robwise** [comment]
100% agree

**Comment by justin808** [comment]
@jbhatab Any chance you can apply Rob's comment?

**Comment by jbhatab** [comment]
I agree.  I think cutting them would be great
