### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by aymericbouzy** [shakacode/react_on_rails#445]
Hi! I did a fresh install and when starting the server with the command : 
```
foreman start -f Procfile.dev
```
I got the following output : 
```
09:15:21 web.1    | started with pid 53027
09:15:21 client.1 | started with pid 53028
09:15:22 client.1 | 
09:15:22 client.1 | > react-webpack-rails-tutorial@0.0.1 build:development /Users/aymericbouzy/Sites/react-on-rails-test/client
09:15:22 client.1 | > webpack -w --config webpack.config.js
09:15:22 client.1 | 
09:15:22 client.1 | Webpack dev build for Rails
09:15:24 web.1    | /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/therubyracer-0.12.2/lib/v8.rb:4:in `require': incompatible library version - /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/therubyracer-0.12.2/lib/v8/init.bundle (fatal)
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/therubyracer-0.12.2/lib/v8.rb:4:in `<top (required)>'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:108:in `require'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:108:in `available?'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/execjs-2.7.0/lib/execjs/runtimes.rb:63:in `each'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/execjs-2.7.0/lib/execjs/runtimes.rb:63:in `find'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/execjs-2.7.0/lib/execjs/runtimes.rb:63:in `best_available'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/execjs-2.7.0/lib/execjs/runtimes.rb:57:in `autodetect'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/uglifier-3.0.0/lib/uglifier.rb:5:in `require'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/uglifier-3.0.0/lib/uglifier.rb:5:in `<top (required)>'
09:15:24 web.1    | 	from /Users/aymericbouzy/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
09:15:24 web.1    | 	from /Users/aymericbouzy/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
09:15:24 web.1    | 	from /Users/aymericbouzy/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
09:15:24 web.1    | 	from /Users/aymericbouzy/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
09:15:24 web.1    | 	from /Users/aymericbouzy/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
09:15:24 web.1    | 	from /Users/aymericbouzy/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
09:15:24 web.1    | 	from /Users/aymericbouzy/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/config/application.rb:7:in `<top (required)>'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:78:in `require'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:78:in `block in server'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:75:in `server'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/railties-4.2.5.1/lib/rails/commands.rb:17:in `<top (required)>'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/bin/rails:9:in `require'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/bin/rails:9:in `<top (required)>'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/spring-1.7.1/lib/spring/client/rails.rb:28:in `load'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/spring-1.7.1/lib/spring/client/rails.rb:28:in `call'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/spring-1.7.1/lib/spring/client/command.rb:7:in `call'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/spring-1.7.1/lib/spring/client.rb:30:in `run'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/spring-1.7.1/bin/spring:49:in `<top (required)>'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/spring-1.7.1/lib/spring/binstub.rb:11:in `load'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/spring-1.7.1/lib/spring/binstub.rb:11:in `<top (required)>'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/bin/spring:13:in `require'
09:15:24 web.1    | 	from /Users/aymericbouzy/Sites/react-on-rails-test/bin/spring:13:in `<top (required)>'
09:15:24 web.1    | 	from bin/rails:3:in `load'
09:15:24 web.1    | 	from bin/rails:3:in `<main>'
09:15:25 web.1    | exited with code 1
09:15:25 system   | sending SIGTERM to all processes
09:15:25 client.1 | terminated by SIGTERM
```
I specified ruby version 2.2.4 in my Gemfile.

Thanks for the help.

**Comment by justin808** [comment]
* Please update to 6.0.2 (just released)
* Try running the commands in the procfile individually.

**Comment by aymericbouzy** [comment]
I did all that : `rails s` is the command that makes it fail.
actually, any rails command seems to raise the same error from v8.

**Comment by justin808** [comment]
The error message:

> 09:15:22 client.1 | Webpack dev build for Rails
> 09:15:24 web.1    | /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/therubyracer-0.12.2/lib/v8.rb:4:in `require': incompatible library version - /Users/aymericbouzy/Sites/react-on-rails-test/vendor/bundle/gems/therubyracer-0.12.2/lib/v8/init.bundle (fatal)

You need to address that.
