### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by gwincr11** [shakacode/react_on_rails#465]
Hello,

Thanks for react on rails, it is great!

I am currently experiencing a bit of a hickup, when ever I start the server and it setsup babel, I am getting an error from path.js.

`11:20:14 client.1      | Hash: 300740813c269fa4bdff

11:20:14 client.1      | Version: webpack 1.13.0

11:20:14 client.1      | Time: 4212ms

11:20:14 client.1      |            Asset       Size  Chunks             Chunk Names

11:20:14 client.1      |    app-bundle.js  230 bytes       0  [emitted]  app

11:20:14 client.1      | vendor-bundle.js     1.8 MB       1  [emitted]  vendor

11:20:14 client.1      |    [0] multi app 28 bytes {0} [built] [1 error]

11:20:14 client.1      |    [0] multi vendor 76 bytes {1} [built]

11:20:14 client.1      |     + 297 hidden modules

11:20:14 client.1      |

11:20:14 client.1      | ERROR in ./app/bundles/MainApp/startup/clientRegistration.jsx

11:20:14 client.1      | Module build failed: TypeError: Path must be a string. Received undefined

11:20:14 client.1      |     at assertPath (path.js:7:11)

11:20:14 client.1      |     at Object.dirname (path.js:1326:5)

11:20:14 client.1      |     at /Users/corygwin/Documents/rails-projects/mursweb/client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:353:36

11:20:14 client.1      |     at /Users/corygwin/Documents/rails-projects/mursweb/client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:375:22

11:20:14 client.1      |     at Array.map (native)

11:20:14 client.1      |     at OptionManager.resolvePresets (/Users/corygwin/Documents/rails-projects/mursweb/client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)

11:20:14 client.1      |     at OptionManager.mergePresets (/Users/corygwin/Documents/rails-projects/mursweb/client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)

11:20:14 client.1      |     at OptionManager.mergeOptions (/Users/corygwin/Documents/rails-projects/mursweb/client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)

11:20:14 client.1      |     at /Users/corygwin/Documents/rails-projects/mursweb/client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:349:14

11:20:14 client.1      |     at /Users/corygwin/Documents/rails-projects/mursweb/client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:369:24

11:20:14 client.1      |     at Array.map (native)

11:20:14 client.1      |     at OptionManager.resolvePresets (/Users/corygwin/Documents/rails-projects/mursweb/client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)

11:20:14 client.1      |     at OptionManager.mergePresets (/Users/corygwin/Documents/rails-projects/mursweb/client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)

11:20:14 client.1      |     at OptionManager.mergeOptions (/Users/corygwin/Documents/rails-projects/mursweb/client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)

11:20:14 client.1      |     at OptionManager.addConfig (/Users/corygwin/Documents/rails-projects/mursweb/client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:207:10)

11:20:14 client.1      |     at OptionManager.findConfigs (/Users/corygwin/Documents/rails-projects/mursweb/client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:413:16)

11:20:14 client.1      |     at OptionManager.init (/Users/corygwin/Documents/rails-projects/mursweb/client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:461:12)

11:20:14 client.1      |     at File.initOptions (/Users/corygwin/Documents/rails-projects/mursweb/client/node_modules/babel-core/lib/transformation/file/index.js:194:75)

11:20:14 client.1      |     at new File (/Users/corygwin/Documents/rails-projects/mursweb/client/node_modules/babel-core/lib/transformation/file/index.js:123:22)

11:20:14 client.1      |     at Pipeline.transform (/Users/corygwin/Documents/rails-projects/mursweb/client/node_modules/babel-core/lib/transformation/pipeline.js:45:16)

11:20:14 client.1      |     at transpile (/Users/corygwin/Documents/rails-projects/mursweb/client/node_modules/babel-loader/index.js:14:22)

11:20:14 client.1      |     at Object.module.exports (/Users/corygwin/Documents/rails-projects/mursweb/client/node_modules/babel-loader/index.js:88:12)

11:20:14 client.1      |  @ multi app

11:20:18 web.1         | Using rack adapter
`

This just started happening today and it doesn't seem to matter what branch I am on. No changes have occured with my application. I did setup a new npm based system yesterday that may have changed a dependency globally. I setup the Serverless package. However I uninstalled it and the problem has persisted.

I have tried running NPM install again and simplifying my app to only show a hello world message from react. Neither have worked.

Any help would be great. This is unfortunately happening at a time when I need to do a quick bug fix but I cannot compile my project :(

Thanks,
Cory

**Comment by gwincr11** [comment]
So even with a completely empty clientRegistration file the error persists.

**Comment by gwincr11** [comment]
If I remove the app: ['./app/bundles/MainApp/startup/clientRegistration'] and just have app: [] the error goes away.

**Comment by gwincr11** [comment]
I also just tried a completely clean install. When starting the server it just hangs forever here:

`
12:02:25 client.1 | Hash: ee4d7624c04589139669
12:02:25 client.1 | Version: webpack 1.13.1
12:02:25 client.1 | Time: 5213ms
12:02:25 client.1 |            Asset     Size  Chunks             Chunk Names
12:02:25 client.1 |    app-bundle.js  3.45 MB       0  [emitted]  app
12:02:25 client.1 | vendor-bundle.js  1.85 MB       1  [emitted]  vendor
12:02:25 client.1 |    [0] multi app 28 bytes {0} [built]
12:02:25 client.1 |    [0] multi vendor 76 bytes {1} [built]
12:02:25 client.1 |     + 580 hidden modules
^@^@
`

**Comment by gwincr11** [comment]
Ok, so I solved this by setting up NVM. Removing all my npm packages and reinstalling.
