### ISSUE TITLE
Error symlink on production deploy

### ISSUE THREAD

**Issue by Tamiyadd** [shakacode/react_on_rails#537]
Hi,
i recently updated from `6.0.5` to `6.1.0` and i started to get the following error on production deploy. I know the new version changed the symlinking process. Can you help me to fix that error? do you need more info?

thanks

```
React On Rails: Symlinking "bootstrap/glyphicons-halflings-regular-e8d24354f6eccb2ee15311da94a8ae81.eot" to "bootstrap/glyphicons-halflings-regular.eot"
rake aborted!
Errno::EEXIST: File exists @ sys_fail2 - (glyphicons-halflings-regular-e8d24354f6eccb2ee15311da94a8ae81.eot, glyphicons-halflings-regular.eot)
/home/deploy/sites/swnew/shared/bundle/ruby/2.1.0/gems/react_on_rails-6.1.0/lib/react_on_rails/assets_precompile.rb:45:in `symlink'
/home/deploy/sites/swnew/shared/bundle/ruby/2.1.0/gems/react_on_rails-6.1.0/lib/react_on_rails/assets_precompile.rb:45:in `block in symlink_file'
/home/deploy/sites/swnew/shared/bundle/ruby/2.1.0/gems/react_on_rails-6.1.0/lib/react_on_rails/assets_precompile.rb:44:in `symlink_file'
/home/deploy/sites/swnew/shared/bundle/ruby/2.1.0/gems/react_on_rails-6.1.0/lib/react_on_rails/assets_precompile.rb:75:in `block in symlink_non_digested_assets'
/home/deploy/sites/swnew/shared/bundle/ruby/2.1.0/gems/react_on_rails-6.1.0/lib/react_on_rails/assets_precompile.rb:70:in `each'
/home/deploy/sites/swnew/shared/bundle/ruby/2.1.0/gems/react_on_rails-6.1.0/lib/react_on_rails/assets_precompile.rb:70:in `symlink_non_digested_assets'
/home/deploy/sites/swnew/shared/bundle/ruby/2.1.0/gems/react_on_rails-6.1.0/lib/tasks/assets.rake:7:in `block (3 levels) in <top (required)>'
/home/deploy/sites/swnew/shared/bundle/ruby/2.1.0/gems/react_on_rails-6.1.0/lib/tasks/assets.rake:50:in `block in <top (required)>'
/home/deploy/sites/swnew/shared/bundle/ruby/2.1.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => react_on_rails:assets:symlink_non_digested_assets
(See full trace by running task with --trace)
rake stderr: Nothing written
```

**Comment by justin808** [comment]
@Tamiyadd Please delete the deployment directory and try again.

I think there's some unexpected file already existing where we're creating the symlinks.

**Comment by Tamiyadd** [comment]
Hi @justin808 
i'm using `capistrano` to deploy my application so every deploy a new release directory is created from scratch

**Comment by justin808** [comment]
@Tamiyadd Can you take a look at https://github.com/shakacode/react_on_rails/blob/master/lib/tasks/assets.rake

You can turn off the automatic usage of that file, per the instructions in the README.md, in regards to the precompilation during deployments.

We'll need your help to debug this.

**Comment by Tamiyadd** [comment]
Hi @justin808 after some try i found that there was a problem in my server with symlinking of files. Now everything is working well!

thanks for the support!
