### ISSUE TITLE
Older version of Rspec throwing an error

### ISSUE THREAD

**Issue by davegonzalez** [shakacode/react_on_rails#540]
Hi again!

Due to our codebase using an older version of rspec - 2.14.8 - tests won't run. I receive the following error:
```
/Users/davidgonzalez/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-2.14.8/lib/rspec/core/hooks.rb:512:in `extract_scope_from': You must explicitly give a scope (:each, :all, or :suite) when using symbols as metadata for a hook. (ArgumentError)
       	from /Users/davidgonzalez/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-2.14.8/lib/rspec/core/hooks.rb:505:in `scope_and_options_from'
       	from /Users/davidgonzalez/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-2.14.8/lib/rspec/core/hooks.rb:483:in `register_hook'
       	from /Users/davidgonzalez/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-2.14.8/lib/rspec/core/hooks.rb:318:in `before'
       	from /Users/davidgonzalez/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/react_on_rails-6.1.0/lib/react_on_rails/test_helper.rb:37:in `block in configure_rspec_to_compile_assets'
       	from /Users/davidgonzalez/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/react_on_rails-6.1.0/lib/react_on_rails/test_helper.rb:36:in `each'
       	from /Users/davidgonzalez/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/react_on_rails-6.1.0/lib/react_on_rails/test_helper.rb:36:in `configure_rspec_to_compile_assets'
       	from /Users/davidgonzalez/VHX/crystal/spec/spec_helper.rb:43:in `block in <top (required)>'
       	from /Users/davidgonzalez/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-2.14.8/lib/rspec/core.rb:120:in `configure'
       	from /Users/davidgonzalez/VHX/crystal/spec/spec_helper.rb:42:in `<top (required)>'
       	from /Users/davidgonzalez/VHX/crystal/spec/services/return_to_sanitizer_spec.rb:1:in `require'
       	from /Users/davidgonzalez/VHX/crystal/spec/services/return_to_sanitizer_spec.rb:1:in `<top (required)>'
       	from /Users/davidgonzalez/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `load'
       	from /Users/davidgonzalez/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `block in load_spec_files'
       	from /Users/davidgonzalez/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `each'
       	from /Users/davidgonzalez/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `load_spec_files'
       	from /Users/davidgonzalez/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:22:in `run'
       	from /Users/davidgonzalez/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:80:in `run'
       	from /Users/davidgonzalez/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:17:in `block in autorun'
``` 

It looks like this version of rspec is expecting :each, :suite, or :all to be passed into the before hook of the `configure_rspec_to_compile_assets` method, as :example wasn't introduced until 3.0. 

```ruby
def self.configure_rspec_to_compile_assets(config, *metatags)
  metatags = [:js, :server_rendering] if metatags.empty?

  metatags.each do |metatag|
    config.before(:example, metatag) { ReactOnRails::TestHelper.ensure_assets_compiled }
  end
end
```

Not sure if this is something you'd want to support, neither am I really sure how you'd want to handle it if you do want to support it. I'm up for ideas if you'd like to see this fixed though!

**Comment by justin808** [comment]
@davegonzalez Please poke around the code. 

I suggest you not run this helper: ReactOnRails::TestHelper.configure_rspec_to_compile_assets

And instead just put the code as needed in your spec_helper.rb.

Does that solve your issue?

**Comment by davegonzalez** [comment]
Sorry! My mistake; removing it definitely allows it to work. Thanks again for the prompt reply!

**Comment by mustmodify** [comment]
Question, though... since the generator adds that line, isn't it important?

**Comment by justin808** [comment]
@mustmodify I think the code checks. Anyway, please open a PR if it's an issue!

**Comment by mustmodify** [comment]
ok. So if I'm understanding your response, that line isn't needed anymore and I should open a PR to remove it from your generator?

**Comment by justin808** [comment]
@mustmodify remove what?
