### ISSUE TITLE
Foreman / Thor Conflict

### ISSUE THREAD

**Issue by ryanking1809** [shakacode/react_on_rails#626]
I've been trying to implement the react_on_rails gem using the tutorial found here: https://youtu.be/_bjScw60FBk

Difference being I'm using ruby 2.3.3, node 7.2.0, and ran the setup with redux (`rails generate react_on_rails:install --redux`)

However now when I try to run foreman using `foreman run -f Procfile.dev` I get the following error:

```
/Users/ryanking/.rvm/gems/ruby-2.3.3/gems/thor-0.19.3/lib/thor/base.rb:534:in `thor_reserved_word?': "run" is a Thor reserved word and cannot be defined as command (RuntimeError)
    from /Users/ryanking/.rvm/gems/ruby-2.3.3/gems/thor-0.19.3/lib/thor/base.rb:597:in `method_added'
    from /Users/ryanking/.rvm/gems/ruby-2.3.3/gems/foreman-0.82.0/lib/foreman/cli.rb:80:in `<class:CLI>'
    from /Users/ryanking/.rvm/gems/ruby-2.3.3/gems/foreman-0.82.0/lib/foreman/cli.rb:11:in `<top (required)>'
    from /Users/ryanking/.rvm/gems/ruby-2.3.3/gems/foreman-0.82.0/bin/foreman:5:in `require'
    from /Users/ryanking/.rvm/gems/ruby-2.3.3/gems/foreman-0.82.0/bin/foreman:5:in `<top (required)>'
    from /Users/ryanking/.rvm/gems/ruby-2.3.3/bin/foreman:22:in `load'
    from /Users/ryanking/.rvm/gems/ruby-2.3.3/bin/foreman:22:in `<main>'
    from /Users/ryanking/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
    from /Users/ryanking/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

Any idea why this is happening & how I could fix it?

**Comment by justin808** [comment]
`foreman start -f Procfile.dev`

**Comment by ryanking1809** [comment]
turns out it's a bug https://github.com/ddollar/foreman/issues/653

**Comment by Saidbek** [comment]
+1 got the same error, using `gem 'thor', '0.19.1'` in Gemfile and it's working ...
