### ISSUE TITLE
FYI: Travis fails the first time without a re-run

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#741]
See: https://github.com/shakacode/react_on_rails/blob/master/.travis.yml

Should I turn off support for Ruby 2.0.0 from Travis?

**Comment by justin808** [comment]
Failures on master:

![2017-02-24_19-08-14](https://cloud.githubusercontent.com/assets/1118459/23328462/838ced40-fac5-11e6-8390-b55c423a7203.png)


Ruby 2.0
![2017-02-24_19-08-32](https://cloud.githubusercontent.com/assets/1118459/23328460/7e375088-fac5-11e6-9a5b-cf86a44b92b6.png)


Ruby 2.2

![2017-02-24_19-09-03](https://cloud.githubusercontent.com/assets/1118459/23328458/788cee68-fac5-11e6-992c-805d6c25e531.png)

**Comment by justin808** [comment]
Another random failure:

```
Failures:
  1) Pages/Index All in one page Server Rendered/Cached React/Redux Component 
     Failure/Error: visit root_path
     
     Net::ReadTimeout:
       Net::ReadTimeout
     Shared Example Group: "React Component" called from ./spec/features/integration_spec.rb:31
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.4/lib/selenium/webdriver/remote/http/default.rb:124:in `response_for'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.4/lib/selenium/webdriver/remote/http/default.rb:78:in `request'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.4/lib/selenium/webdriver/remote/http/common.rb:63:in `call'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.4/lib/selenium/webdriver/remote/bridge.rb:645:in `raw_execute'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.4/lib/selenium/webdriver/remote/bridge.rb:109:in `create_session'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.4/lib/selenium/webdriver/remote/bridge.rb:69:in `initialize'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.4/lib/selenium/webdriver/chrome/bridge.rb:42:in `initialize'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.4/lib/selenium/webdriver/common/driver.rb:61:in `new'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.4/lib/selenium/webdriver/common/driver.rb:61:in `for'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.4/lib/selenium/webdriver.rb:82:in `for'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/capybara-2.7.1/lib/capybara/selenium/driver.rb:14:in `browser'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/capybara-2.7.1/lib/capybara/selenium/driver.rb:46:in `visit'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/capybara-2.7.1/lib/capybara/session.rb:233:in `visit'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/capybara-2.7.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
     # ./spec/features/integration_spec.rb:27:in `block (3 levels) in <top (required)>'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/rspec-retry-0.5.2/lib/rspec/retry.rb:112:in `block in run'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/rspec-retry-0.5.2/lib/rspec/retry.rb:101:in `loop'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/rspec-retry-0.5.2/lib/rspec/retry.rb:101:in `run'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/rspec-retry-0.5.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # /home/travis/.rvm/gems/ruby-2.3.1/gems/rspec-retry-0.5.2/lib/rspec/retry.rb:30:in `block (2 levels) in setup'
Finished in 2 minutes 5.6 seconds (files took 5.41 seconds to load)
75 examples, 1 failure
Failed examples:
rspec ./spec/features/integration_spec.rb[1:1:1:1] # Pages/Index All in one page Server Rendered/Cached React/Redux Component 
Coverage report generated for dummy, gem-tests to /home/travis/build/shakacode/react_on_rails/coverage. 734 / 881 LOC (83.31%) covered.
rake aborted!
Command failed with status (1): [cd /home/travis/build/shakacode/react_on_r...]
/home/travis/build/shakacode/react_on_rails/rakelib/task_helpers.rb:20:in `block in sh_in_dir'
/home/travis/build/shakacode/react_on_rails/rakelib/task_helpers.rb:20:in `each'
/home/travis/build/shakacode/react_on_rails/rakelib/task_helpers.rb:20:in `sh_in_dir'
/home/travis/build/shakacode/react_on_rails/rakelib/run_rspec.rake:107:in `run_tests_in'
/home/travis/build/shakacode/react_on_rails/rakelib/run_rspec.rake:23:in `block (2 levels) in <top (required)>'
/home/travis/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => run_rspec => run_rspec:run_rspec => run_rspec:all_but_examples => run_rspec:dummy
(See full trace by running task with --trace)
The command "rake" exited with 1.
cache.2
store build cache
$ bundle clean
Cleaning all the gems on your system is dangerous! If you're sure you want to remove every system gem not in this bundle, run `bundle clean --force`.
0.00s
2.07snothing changed, not updating cache
Done. Your build exited with 1.
```

**Comment by justin808** [comment]
Closing for now. No solution found other than clicking that re-run button.
