### ISSUE TITLE
Webpack 2.3 is breaking builds

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#770]
See #768.

The `^` in the webpack config is resulting in the use of 2.3.x for Webpack and that gives this error:

```
-react-jsx-self@^6.22.0-flow-strip-types@^6.22.0atch the API schema.
- configuration.output.path: The provided value "../app/assets/webpack" is not an absolute path!
icromatch@^2.1.5ap@0.0.1-browserify@0.0.4inimalistic-crypto-utils@^1.0.0[2/4] Fetching packages...
warning fsevents@1.1.1: The platform "linux" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
e/rof/src/github.com/shakacode/react_on_rails/gen-examples/examples/basic/client && $(yarn bin)/webpack --config webpack.config.js
info No lockfile found.
[1/4] Resolving packages...
ap@^0.5.6atch the API schema.
- configuration.output.path: The provided value "../app/assets/webpack" is not an absolute path!
rake aborted!
Command failed with status (1): [cd /home/rof/src/github.com/shakacode/reac...]
/home/rof/src/github.com/shakacode/react_on_rails/rakelib/task_helpers.rb:20:in `block in sh_in_dir'
/home/rof/src/github.com/shakacode/react_on_rails/rakelib/task_helpers.rb:20:in `each'
/home/rof/src/github.com/shakacode/react_on_rails/rakelib/task_helpers.rb:20:in `sh_in_dir'
/home/rof/src/github.com/shakacode/react_on_rails/rakelib/examples.rake:40:in `block (3 levels) in <top (required)>'
/home/rof/src/github.com/shakacode/react_on_rails/rakelib/examples.rake:34:in `block (4 levels) in <top (required)>'
Tasks: TOP => examples:build_webpack_bundles_basic
(See full trace by running task with --trace)
```
https://app.codeship.com/projects/187011/builds/23733772

The short-term fix is to lock Webpack at 2.2.1.

We'll be updating to 2.3.1 shortly.

**Comment by cheremukhin23** [comment]
The issue is caused by breaking change in Webpack itself.
The output.path required to be an absolute path in webpack v2
In webpack 2.2.x there was no absolute path validation, but in 2.3.x it is added.

Here is my PR to fix this issue
https://github.com/shakacode/react_on_rails/pull/771
