### ISSUE TITLE
 yarn run build:test fails on linux

### ISSUE THREAD

**Issue by cshupp1** [shakacode/react_on_rails#910]
I am quite new to react on rails, so user error is a great possibility...
When running 'yarn run build:test' on windows it works.

When running the build on linux:
```
[INFO] Running: yarn run build:test
[INFO] yarn run v0.24.5
[INFO] $ webpack --config webpack.config.js 
[INFO] /app/jenkins/jobs/prisme_log_event/workspace/client/webpack.config.js:6
[INFO] const { resolve } = require('path');
[INFO]       ^
[INFO] SyntaxError: Unexpected token {
[INFO]     at exports.runInThisContext (vm.js:53:16)
[INFO]     at Module._compile (module.js:374:25)
[INFO]     at Object.Module._extensions..js (module.js:417:10)
[INFO]     at Module.load (module.js:344:32)
[INFO]     at Function.Module._load (module.js:301:12)
[INFO]     at Module.require (module.js:354:17)
[INFO]     at require (internal/module.js:12:17)
[INFO]     at requireConfig (/app/jenkins/jobs/prisme_log_event/workspace/client/node_modules/webpack/bin/convert-argv.js:96:18)
[INFO]     at /app/jenkins/jobs/prisme_log_event/workspace/client/node_modules/webpack/bin/convert-argv.js:109:17
[INFO]     at Array.forEach (native)
[INFO] error Command failed with exit code 1.
[INFO] rake aborted!
[INFO] Command failed with status (1): [yarn run build:test...]
[INFO] /app/jenkins/jobs/prisme_log_event/workspace/lib/rails_common/tasks/build_helper.rake:40:in `block in (root)'
[INFO] /app/jenkins/jobs/prisme_log_event/workspace/lib/rails_common/tasks/build_helper.rake:39:in `block in (root)'
```

I am unsure how to handle this.  Any ideas?  It appears I really need to do this before running my tests.

Thanks,

Cris

**Comment by justin808** [comment]
@cshupp1 you probably don't have babel correctly configured. We'd have to debug this.

If you want personalized help on this, please consider our [Coaching Plan](http://www.shakacode.com/work/shakacode-coaching-plan.pdf).
