### ISSUE TITLE
Packs building on deploy starts before yarn install

### ISSUE THREAD

**Issue by gambala** [shakacode/react_on_rails#966]
And we get an error, when there is no react-on-rails package on the server. On first deploy, for example.

Capistrano stacktrace:

```
00:22 deploy:assets:precompile
      01 ~/.rvm/bin/rvm default do bundle exec rake assets:precompile
      01 [tunemygc] not enabled
      01
      01 ReactOnRails: Set generated_assets_dir to default: public/webpack/staging
      01
      01 RAILS_ENV=production bin/webpack
      01
      01 yarn run v0.27.5
      01 $ "/home/deployer/apps/melp-staging/releases/20171027165215/node_modules/.bin/webpack" "--config" "/home/deployer/apps/melp-st…
      01 Hash: 3c0726ccfad80d487dd3
      01 Version: webpack 3.8.1
      01 Time: 80437ms
      01                                   Asset       Size  Chunks                    Chunk Names
      01     application-ad46f3eb889c6ca33df4.js    1.07 MB       0  [emitted]  [big]  application
      01 application-ad46f3eb889c6ca33df4.js.map    1.47 MB       0  [emitted]         application
      01                           manifest.json  142 bytes          [emitted]
      01                        manifest.json.gz   88 bytes          [emitted]
      01  application-ad46f3eb889c6ca33df4.js.gz     291 kB          [emitted]  [big]
      01   [31] (webpack)/buildin/global.js 488 bytes {0} [built]
      01   [50] (webpack)/buildin/module.js 495 bytes {0} [built]
      01  [187] ./app/javascript/packs/application.js + 173 modules 544 kB {0} [built]
      01  [188] ./app/javascript/bundles/modernizr.js 3.93 kB {0} [built]
      01  [194] (webpack)/buildin/amd-options.js 80 bytes {0} [built]
      01  [472] /home/deployer/apps/melp-staging/shared/node_modules/dom-align/es/index.js + 8 modules 31.8 kB {0} [built]
      01     + 515 hidden modules
      01
      01 ERROR in ./app/javascript/packs/application.js
      01 Module not found: Error: Can't resolve 'react-on-rails' in '/home/deployer/apps/melp-staging/releases/20171027165215/app/javas…
      01  @ ./app/javascript/packs/application.js 7:0-42
      01
      01 ERROR in ./app/javascript/scripts/ujs.js
      01 Module not found: Error: Can't resolve 'react-on-rails' in '/home/deployer/apps/melp-staging/releases/20171027165215/app/javas…
      01  @ ./app/javascript/scripts/ujs.js 1:0-42
      01  @ ./app/javascript/packs/application.js
      01 error Command failed with exit code 2.
      01 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
      01 rake aborted!
      01 Command failed with status (1): [RAILS_ENV=production bin/webpack...]
      01 /home/deployer/apps/melp-staging/shared/bundle/ruby/2.4.0/gems/react_on_rails-10.0.0/lib/tasks/assets.rake:64:in `block (3 lev…
      01 /home/deployer/apps/melp-staging/shared/bundle/ruby/2.4.0/gems/bugsnag-5.4.1/lib/bugsnag/rake.rb:12:in `execute_with_bugsnag'
      01 /home/deployer/apps/melp-staging/shared/bundle/ruby/2.4.0/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
      01 /home/deployer/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
      01 /home/deployer/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
      01 /home/deployer/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
      01 /home/deployer/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
      01 /home/deployer/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      01 /home/deployer/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      01 /home/deployer/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
      01 /home/deployer/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
      01 /home/deployer/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
      01 /home/deployer/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
      01 /home/deployer/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
      01 /home/deployer/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
      01 /home/deployer/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
      01 /home/deployer/.rvm/gems/ruby-2.4.1/bin/bundle:23:in `load'
      01 /home/deployer/.rvm/gems/ruby-2.4.1/bin/bundle:23:in `<main>'
      01 /home/deployer/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
      01 /home/deployer/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
      01 Tasks: TOP => assets:precompile => react_on_rails:assets:compile_environment => react_on_rails:assets:webpack
      01 (See full trace by running task with --trace)
```

My (dirty but) workaround:

1. Set `config.build_production_command` config to `nil`.
2. Deploy.
3. Restore `config.build_production_command` config value.
4. Deploy as usual.

**Comment by justin808** [comment]
@gambala Does this require a Doc update or a PR?

**Comment by gambala** [comment]
PR, if it's possible to swap yarn installing and webpack building tasks in different order.

**Comment by railsme** [comment]
Where are the versions of dependencies? capistrano, capistrano-rails?
Do you have internal assets pipeline enabled?
What is your capistrano configuration?
Is it a clean rails project or existing one?

**Comment by gambala** [comment]
Existing RoR project with rails assets pipeline enabled (for styles/fonts/images mostly)
- ruby 2.4.1
- capistrano (3.10.0)
- capistrano-rails (1.3.0)
- execjs (2.7.0)
- libv8 (5.9.211.38.1)
- mini_racer (0.1.14)
- rails (5.1.4)
- webpacker (3.0.2)

`Capfile`

```
# frozen_string_literal: true

require 'capistrano/setup'
require 'capistrano/deploy'
require 'capistrano/scm/git'
require 'capistrano/rvm'
require 'capistrano/bundler'
require 'capistrano/rails/assets'
require 'capistrano/rails/migrations'
require 'capistrano/rails/console'
require 'capistrano/figaro_yml'
require 'capistrano/sitemap_generator'
require 'capistrano/puma'
require 'whenever/capistrano'
require 'slackistrano/capistrano'
require_relative 'lib/slackistrano/custom_messaging'

Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }
install_plugin Capistrano::SCM::Git
install_plugin Capistrano::Puma
install_plugin Capistrano::Puma::Monit
install_plugin Capistrano::Puma::Nginx
```

`deploy.rb`

```
set :application, 'melp'
set :branch, (proc { `git rev-parse --abbrev-ref HEAD`.chomp })
set :deploy_to, "/home/deployer/apps/#{fetch(:application)}-#{fetch(:stage)}"
set :linked_dirs, %w(...)
set :linked_files, %w(...)
set :log_level, :info
set :puma_bind, "unix://#{shared_path}/tmp/sockets/#{fetch(:application)}-puma.sock"
set :puma_init_active_record, true
set :puma_preload_app, false
set :puma_threads, [4, 16]
set :puma_workers, 2
set :repo_url, 'git@github.com:melp-pro/melp-rails.git'
set :slackistrano,
    klass: Slackistrano::CustomMessaging,
    channel: '#general',
    webhook: '...'
set :support_email, 'hello@melp.pro'
set :user, 'deployer'
set :whenever_identifier, -> { "#{fetch(:application)}-#{fetch(:stage)}" }
```

`deploy/production.rb`

```
server '...', user: '...', port: ..., roles: %w(app db web)
set :letsencrypt_path, '...'
set :nginx_config_name, '...'
set :nginx_server_name, '...'
set :nginx_use_ssl, true
set :ssh_options, ...
```

**Comment by railsme** [comment]
@gambala thanks. It will help to reproduce the problem.

**Comment by esshka** [comment]
try 
`namespace :react_on_rails do
  namespace :assets do
    task webpack: 'webpacker:yarn_install' if Rake::Task.task_defined?('webpacker:yarn_install')
  end
end`

**Comment by Whyves** [comment]
@gambala , @justin808 with the release of react_on_rails 10.x, are the symlink tasks still required? I would assume that with webpacker 3, react_on_rails should rely on the webpacker gem to do the compilation.

I have a problem pushing to Heroku because yarn isn't run at deployment time or at least isn't run before your react_on_rails:assets:webpack task.

In your assets.rake file, you add the react_on_rails:assets:webpack task as a prerequisite to assets:precompile which runs before the railties' yarn:install task (also a prerequisite).

Also, by using your own webpack task, you bypass any configuration that we would put in webpacker.

I think that we should have a config flag to would allow ignore the react_on_rails compilation. Would that make sense?

**Comment by justin808** [comment]
The symlinking is not done per this line: https://github.com/shakacode/react_on_rails/blob/0e064616ad387b921f78707cc054f92ed987add3/lib/react_on_rails/assets_precompile.rb#L66

```
  def symlink_non_digested_assets
      # digest ==> means that the file has a unique sha so the browser will load a new copy.
      # Webpack's CSS extract-text-plugin copies digested asset files over to directory where we put
      # we deploy the webpack compiled JS file. Since Rails will deploy the image files in this
      # directory with a digest, then the files are essentially "double-digested" and the CSS
      # references from webpack's CSS would be invalid. The fix is to symlink the double-digested
      # file back to the original digested name, and make a similar symlink for the gz version.
      return unless @symlink_non_digested_assets_regex
```

Does this answer your question?

Documented here: https://github.com/shakacode/react_on_rails/blob/44e697018b5452d8198731c9201ffbbc2041ed60/README.md#deployment


> config.symlink_non_digested_assets_regex: Set to nil to turn off the setup of non-js assets.

Let me know if we can close this issue or if a PR is suggested.

**Comment by Whyves** [comment]
Hi @justin808 ,

Sorry, I guess I was not precise enough. Yes, I know that we can turn the symlink and compilation to off by setting some values to nil. However, the problem arises because of these lines in [assets.rake](https://github.com/shakacode/react_on_rails/blob/master/lib/tasks/assets.rake):

```
  # These tasks run as pre-requisites of assets:precompile.
  # Note, it's not possible to refer to ReactOnRails configuration values at this point.
  Rake::Task["assets:precompile"]
    .clear_prerequisites
    .enhance([:environment, "react_on_rails:assets:compile_environment"])
    .enhance do
      Rake::Task["react_on_rails:assets:symlink_non_digested_assets"].invoke
      Rake::Task["react_on_rails:assets:delete_broken_symlinks"].invoke
    end
end

```

This section of code will run no matter what and by doing so will erase all the prerequisites from **assets:precompile**. This in turn removes the **yarn:intall** prerequisite and even cleans up the webpacker compile task.

```
if Rake::Task.task_defined?("webpacker:compile")
   # TODO: Eventually, this will need reconsideration if we use any of the Webpacker compilation
   Rake::Task["webpacker:compile"].clear
end

```
I'm thus left with a broken webpacker. So, I was basically asking if there are such a need to overwrite the compilation process anymore. From what I could read, you had to do this for pre webpacker3. If it's not required anymore for Webpacker 3, maybe there could be a way to completely turn this off so that I can rely solely on Webpacker to build my system.

I know that I could somehow override the tasks' actions and prerequisite but I would rather not do that in order to easy upgrades to gems along the way.

**Comment by justin808** [comment]
The overriding of the default webpacker task is intentional. I suggest opening up a new issue on this and carefully presenting your case.

Why do you say webpacker is broken?
