### ISSUE TITLE
Upload the app to heroku the compiling is failed 

### ISSUE THREAD

**Issue by Champer** [shakacode/react_on_rails#996]
I got the error as following, and I had no idea to fix it...
Anybody can tell me what happened is it?
```
remote:        The latest bundler is 1.16.0, but you are currently running 1.15.2.
remote:        To update, run `gem install bundler`
remote:        /tmp/build_5251094d659216fd08844f0fdeb39442/vendor/bundle/ruby/2.4.0/gems/webpacker-3.1.1/lib/webpacker/webpack_runner.rb:11:in `exec': No such file or directory - /tmp/build_5251094d659216fd08844f0fdeb39442/node_modules/.bin/webpack (Errno::ENOENT)
remote:        from /tmp/build_5251094d659216fd08844f0fdeb39442/vendor/bundle/ruby/2.4.0/gems/webpacker-3.1.1/lib/webpacker/webpack_runner.rb:11:in `block in run'
remote:        from /tmp/build_5251094d659216fd08844f0fdeb39442/vendor/bundle/ruby/2.4.0/gems/webpacker-3.1.1/lib/webpacker/webpack_runner.rb:10:in `chdir'
remote:        from /tmp/build_5251094d659216fd08844f0fdeb39442/vendor/bundle/ruby/2.4.0/gems/webpacker-3.1.1/lib/webpacker/webpack_runner.rb:10:in `run'
remote:        from /tmp/build_5251094d659216fd08844f0fdeb39442/vendor/bundle/ruby/2.4.0/gems/webpacker-3.1.1/lib/webpacker/runner.rb:6:in `run'
remote:        from /tmp/build_5251094d659216fd08844f0fdeb39442/vendor/bundle/ruby/2.4.0/gems/webpacker-3.1.1/exe/webpack:8:in `<top (required)>'
remote:        from bin/webpack:21:in `load'
remote:        from bin/webpack:21:in `<main>'
remote:        rake aborted!
remote:        Command failed with status (1): [cd /tmp/build_5251094d659216fd08844f0fdeb3...]
remote:        /tmp/build_5251094d659216fd08844f0fdeb39442/vendor/bundle/ruby/2.4.0/gems/react_on_rails-10.0.2/lib/tasks/assets.rake:64:in `block (3 levels) in <top (required)>'
remote:        /tmp/build_5251094d659216fd08844f0fdeb39442/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
remote:        Tasks: TOP => assets:precompile => react_on_rails:assets:compile_environment => react_on_rails:assets:webpack
remote:        (See full trace by running task with --trace)
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !	Push rejected to serene-dawn-50490.
remote:
To https://git.heroku.com/serene-dawn-50490.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/serene-dawn-50490.git'
```

**Comment by justin808** [comment]
@Champer you're using the default webpacker configuration. I know there were some issues with webpacker and the bin stub. Please search the issues here. This has been brought up before.
